services:
  postgresdb:
    image: postgres:16-alpine
    container_name: postgresdb
    restart: always
    environment:
      - POSTGRES_DB=blog_db
      - POSTGRES_USER=bloguser
      - POSTGRES_PASSWORD=blogpassword
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

 

volumes:
  postgres_data: